#!/usr/bin/env bash

set -e

MY_SHELL=$( which bash )

/usr/sbin/useradd -c 'Matt Willsher,,matt@willsher.systems,' -s ${MY_SHELL} -m mattw
cat >/etc/sudoers.d/mattw-ALL <<EOF
mattw     ALL=(ALL:ALL) NOPASSWD: ALL
EOF
chmod 0440 /etc/sudoers.d/mattw-ALL
mkdir ~mattw/.ssh
chmod 700 ~mattw/.ssh
curl https://raw.githubusercontent.com/mattwillsher/ssh_access/master/mattw_ssh_pub_key >~mattw/.ssh/authorized_keys
chmod 400 ~mattw/.ssh/authorized_keys
chown -R mattw ~mattw/.ssh
